# Generated by Django 4.2.7 on 2025-04-15 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='dept',
            new_name='department',
        ),
    ]
